service: sls-hello-world

provider:
  name: aws
  runtime: nodejs8.10
  profile: marcia


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/GreetNames"


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  wasGreeted:
    handler: handler.wasGreeted
    events:
      - http:
          path: wasGreeted
          method: get

resources:
  Resources:
    GreetNamesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "GreetNames"
